### PR TITLE
Adds playbook to setup an Ansible jump host

### PR DESCRIPTION
**Pull request by vvaldez**
Spawns a single AWS VM based on the RHEL AMI and installs an Ansible environment with git to use for running playbooks. Call this playbook the same way as the other AMI options, but specify `ami_config=ansible_host`. This does not currently create an AMI out of this ansible host but we could discuss adding that.

Example command:
```
AMIVER=1
ansible-playbook ami_lab_launch.yml -e @secrets.yml -e @vvaldez-secrets-sysdeseng.yml -e ami_unique_id=$(( AMIVER +=1 )) -e ami_user=vvaldez -e ami_config=ansible_host
```

### CODE REVIEW

**Comment by vvaldez** [comment]
FYI I am on a plane with a very slow connection. Ironically this is the ideal use case for this Ansible jump box. In any case, 3 runs in a row timeout during yum install with:

```
TASK [Install yum packages] *****************************************************************************************************
Friday 06 April 2018  13:10:22 -0400 (0:00:25.464)       0:02:51.395 **********
Friday 06 April 2018  13:10:22 -0400 (0:00:25.464)       0:02:51.393 **********
failed: [vvaldez-ansible-host.labs.sysdeseng.com] (item=[u'wget', u'git', u'net-tools', u'bind-utils', u'bash-completion', u'ansible', u'python-boto3', u'python-boto']) => {"item": ["wget", "git", "net-tools", "bind-utils", "bash-completion", "ansible", "python-boto3", "python-boto"], "msg": "SSH Error: data could not be sent to remote host \"13.57.28.8\". Make sure this host can be reached over ssh", "unreachable": true}
fatal: [vvaldez-ansible-host.labs.sysdeseng.com]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_ignore_errors": null, "_ansible_item_result": true, "item": ["wget", "git", "net-tools", "bind-utils", "bash-completion", "ansible", "python-boto3", "python-boto"], "msg": "SSH Error: data could not be sent to remote host \"13.57.28.8\". Make sure this host can be reached over ssh", "unreachable": true}]}
```

However, the VM is still accessible. Curious if this happens to you with a good connection.

**Comment by scollier** [comment]
LGTM.  I tested it. Would like to wait on merging until we finalize where / how it lands.

**Comment by vvaldez** [comment]
@scollier added it to the ami_config role as suggested, ready to test. We can discuss before merging to see if we should make any more changes. E.g. create an AMI out of this? Or add a git clone in here for this and other repos?

**Comment by scollier** [comment]
@vvaldez getting this:

```
 _____________________________________
< TASK [ami_config : Copy git prompt] >
 -------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Thursday 12 April 2018  15:27:05 -0500 (0:05:30.382)       0:08:48.671 ******** 
Thursday 12 April 2018  15:27:05 -0500 (0:05:30.382)       0:08:48.670 ******** 
fatal: [ami-bthurber-ansible_host-3.labs.sysdeseng.com]: FAILED! => {"msg": "The field 'become_user' has an invalid value, which includes an undefined variable. The error was: 'ansible_user' is undefined"}
```

**Comment by scollier** [comment]
@vvaldez regardless of the error above, i'd like to get this PR merged in without blocking on additional functionality.  we can add that later.

**Comment by vvaldez** [comment]
@scollier found and fixed the error, please re-test.

**Comment by vvaldez** [comment]
LGTM, merging so the following PR can be rebased.

**Pull request merged**
